name: GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
    
    - name: Start localhost server
      run: npm start &

    - name: Wait for localhost to be available
      run: sleep 10

    - name: Run E2E tests
      run: npm run cypress-e2e
      
    - name: Run cypress
      run: npm run cypress-component

    - name: Build
      run: npm run build:prod
